apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqldb
data:
  connection-name: qwiklabs-gcp-01-18980c4e76f7:us-central1:marketplace=tcp:3306
  project-id: qwiklabs-gcp-01-18980c4e76f7
  profile: staging