apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqldb
data:
  connection-name: qwiklabs-gcp-04-8572a3684719:us-central1:marketplace=tcp:3306
  project-id: qwiklabs-gcp-04-8572a3684719
  profile: staging