--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: elastic-app
  name: elastic-app
spec: 
  replicas: 5
  selector:
    matchLabels:
      app: elastic-app
  template: 
    metadata: 
      labels: 
        app: elastic-app
    spec: 
      containers: 
        - name: elastic-app
          image: gcr.io/$(PROJECT_ID)/elastic-app:latest
          imagePullPolicy: Always
          ports: 
            - containerPort: 8080
          env:
            - name: SECRETS_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-user-credentials
                  key: username
            - name: SECRETS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-user-credentials
                  key: password
            - name: CONNECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysqldb
                  key: connection-name  
            - name: PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: mysqldb
                  key: project-id  
            - name: PROFILE
              valueFrom:
                configMapKeyRef:
                  name: mysqldb
                  key: profile                            
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy", "-instances=qwiklabs-gcp-01-18980c4e76f7:us-central1:marketplace=tcp:3306", "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: secrets-volume
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: secrets-volume
          secret:
            secretName: cloudsql-proxy-credentials
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: elastic-app 
data:
  database: marketplace
---
apiVersion: v1
kind: Service
metadata:
  name: elastic-app
spec:
  selector:
    app: elastic-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer